FROM centos

RUN \
    yum -y install \
    httpd \
    php \
    php-cli \
    php-common \
    mod_ssl \
    openssl

RUN echo "<?php phpinfo(); ?>" > /var/www/html/hola.php

COPY startbootstrap-sb-admin-2 /var/www/html
CMD apachectl -DFOREGROUND

